name: setupanewsite
favicon: null
layout_spectrum: 0.00303
typography_spectrum: 0.00101
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.014152188785374165
  lightness: 0.689231792697683
  saturation: 0.1985364151187241
  rhythmicContrast: 0.9693155933637172
purpose: []
