name: setupanewsite
favicon: null
layout_spectrum: 1
typography_spectrum: 0.00101
title: clunky and very buggy  thegrid.io
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffca86'
    - '#29a2ab'
    - '#f09662'
    - '#ce596c'
    - '#7fd2a6'
  brandStrength: 0.014152188785374165
  lightness: 0.689231792697683
  saturation: 0.5
  rhythmicContrast: 0.9693155933637172
purpose: []
