name: setupanewsite
favicon: null
layout_spectrum: 1
typography_spectrum: 0.00505
title: clunky and very buggy  thegrid.io
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00b0f9'
    - '#fefefe'
    - '#c9f2ff'
    - '#98e5ff'
    - '#6cd9ff'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.9693155933637172
purpose: []
